<?php

return [
    [
        'id' => 'server_info',
        'label' => 'Server Information',
        'value' => '',
        'type' => 'text',
        'tooltip_text' => 'Information about the web server that is currently hosting your site.',
        'category' => 'server',
    ],
    [
        'id' => 'php_version',
        'label' => 'PHP Version',
        'value' => '',
        'type' => 'text',
        'tooltip_text' => 'The version of PHP installed on your hosting server.',
        'category' => 'server',
    ],
    [
        'id' => 'php_time_limit',
        'label' => 'PHP Time Limit',
        'value' => '',
        'type' => 'text',
        'tooltip_text' => 'The amount of time (in seconds) that your site will spend on a single operation before timing out (to avoid server lockups)',
        'category' => 'server',
    ],
    [
        'id' => 'wordpress_version',
        'label' => 'Wordpress Version',
        'value' => '',
        'type' => 'text',
        'tooltip_text' => 'The version of Wordpress installed on your hosting server.',
        'category' => 'unify',
    ],
    [
        'id' => 'woocommerce_version',
        'label' => 'Woocommerce Version',
        'value' => '',
        'type' => 'text',
        'tooltip_text' => 'The version of Woocommerce installed on your hosting server.',
        'category' => 'unify',
    ],
    [
        'id' => 'curl_version',
        'label' => 'cURL Version',
        'value' => '',
        'type' => 'text',
        'tooltip_text' => 'The version of cURL installed on your server.',
        'category' => 'server',
    ],
    [
        'id' => 'mysql_version',
        'label' => 'MySQL Version',
        'value' => '',
        'type' => 'text',
        'tooltip_text' => 'The version of MySQL installed on your hosting server.',
        'category' => 'server',
    ],
    [
        'id' => 'max_upload_size',
        'label' => 'Max Upload Size',
        'value' => '',
        'type' => 'size',
        'tooltip_text' => 'The largest filesize that can be uploaded to your WordPress installation.',
        'category' => 'server',
    ],
    [
        'id' => 'wp_memory_limit',
        'label' => 'Wordpress Memory Limit',
        'value' => '',
        'type' => 'size',
        'tooltip_text' => 'The maximum amount of memory (RAM) that your site can use at one time.',
        'category' => 'unify',
    ],
    [
        'id' => 'wp_cron',
        'label' => 'Wordpress cron',
        'value' => '',
        'type' => 'size',
        'tooltip_text' => 'Displays whether or not WP Cron Jobs are enabled.',
        'category' => 'unify',
        'hide_value' => true,
    ],
    [
        'id' => 'log_directory',
        'label' => 'Log Directory',
        'value' => '',
        'type' => 'text',
        'tooltip_text' => 'Several WooCommerce extensions can write logs which makes debugging problems easier. The directory must be writable for this to happen.',
        'category' => 'unify',
    ],
];
